services:
    #listener
    fi.corebundle.kernel.listener.response:
        class: Fi\CdfExtrasecurityBundle\Listener\ResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
